if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_options(${MAIN_TARGET} PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
endif()

set_property(TARGET ${MAIN_TARGET} PROPERTY CUDA_STANDARD ${CMAKE_CXX_STANDARD})
