if(DEFINED ENV{VCPKG_ROOT} AND DEFINED CMAKE_TOOLCHAIN_FILE_VCPKG)
    set(CMAKE_TOOLCHAIN_FILE "${CMAKE_TOOLCHAIN_FILE_VCPKG}" CACHE STRING "" FORCE)
else()
    set(CMAKE_TOOLCHAIN_FILE "${CMAKE_TOOLCHAIN_FILE_CONAN}")
endif()

message("")
message("--> CMake toolchain is " ${CMAKE_TOOLCHAIN_FILE})
message("")
